// Copyright © Aptos Foundation
// SPDX-License-Identifier: Apache-2.0

// Increase recursion limit for `serde_json::json!` macro parsing
#![recursion_limit = "256"]

// #[macro_use]
// extern crate diesel_migrations;

// Need to use this for because src/schema.rs uses the macros and is autogenerated
#[macro_use]
extern crate diesel;

// for parquet_derive
extern crate parquet;
#[macro_use] 
extern crate parquet_derive;

pub use config::IndexerGrpcProcessorConfig;

mod config;
pub mod gap_detector;
pub mod grpc_stream;
pub mod models;
pub mod processors;
pub mod schema;
pub mod transaction_filter;
pub mod utils;
pub mod worker;
pub mod schemas;
