---
coverage:
  # range for color spectrum display, red=50%, green=80%
  range: "50...80"
  precision: 1

  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
    changes: false
