services:
  index-processor:
    image: ghcr.io/byzantion-xyz/aptos-indexer-processors:develop
    restart: on-failure
    container_name: byz-aptos-indexer-processors
    volumes:
      - ./config.yml:/config.yml
    command: "-c /config.yml"
