services:
  index-processor:
    image: ghcr.io/byzantion-xyz/aptos-indexer-processors:develop
    restart: on-failure
    healthcheck:
      test: curl --fail http://localhost:8084 || exit 1
      interval: 60s
      timeout: 5s
      retries: 5

    volumes:
      - ./config.yml:/config.yml
    command: "-c /config.yml"
