health_check_port: 8088
server_config:
  processor_status_checker_config:
    # Endpoint is one of:
    # - https://indexer.mainnet.aptoslabs.com/api/rest/get_lastest_processor_status
    # - https://indexer-testnet.staging.gcp.aptosdev.com/api/rest/get_lastest_processor_status
    # - https://indexer-devnet.staging.gcp.aptosdev.com/api/rest/get_lastest_processor_status
    hasura_rest_api_endpoint: "https://indexer.mainnet.aptoslabs.com/api/rest/get_lastest_processor_status"
    # fullnode_rest_api_endpoint is one of
    # - https://fullnode.mainnet.aptoslabs.com/v1
    # - https://fullnode.testnet.aptoslabs.com/v1
    # - https://fullnode.devnet.aptoslabs.com/v1
    fullnode_rest_api_endpoint: "https://fullnode.mainnet.aptoslabs.com/v1"
