//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::{
    events::Entity as Events, transactions::Entity as Transactions,
    write_set_changes::Entity as WriteSetChanges,
    write_set_changes_module::Entity as WriteSetChangesModule,
    write_set_changes_resource::Entity as WriteSetChangesResource,
    write_set_changes_table::Entity as WriteSetChangesTable,
};
