name: "Docker build setup"
description: |
  Runs an opinionated and unified docker build setup action. It does the following:
  * Logs in to docker image registries GCP GAR
inputs:
  # GCP auth
  GCP_WORKLOAD_IDENTITY_PROVIDER:
    required: true
    description: "GCP Workload Identity provider"
  GCP_SERVICE_ACCOUNT_EMAIL:
    required: true
    description: "GCP service account email"

runs:
  using: composite
  steps:
    - id: auth
      name: "Authenticate to Google Cloud"
      uses: "google-github-actions/auth@dac4e13deb3640f22e3ffe758fd3f95e6e89f712" # pin@v0
      with:
        create_credentials_file: false
        token_format: "access_token"
        access_token_lifetime: 5400 # setting this to 1.5h since sometimes docker builds (special performance builds etc.) take that long. Default is 1h.
        workload_identity_provider: ${{ inputs.GCP_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ inputs.GCP_SERVICE_ACCOUNT_EMAIL }}

    - name: Login to US multi-region Google Artifact Registry
      uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b # pin@v2
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
