# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aptos/datastream/v1/datastream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aptos.util.timestamp import timestamp_pb2 as aptos_dot_util_dot_timestamp_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$aptos/datastream/v1/datastream.proto\x12\x13\x61ptos.datastream.v1\x1a$aptos/util/timestamp/timestamp.proto\"R\n\x12TransactionsOutput\x12<\n\x0ctransactions\x18\x01 \x03(\x0b\x32&.aptos.datastream.v1.TransactionOutput\"t\n\x11TransactionOutput\x12\x1a\n\x12\x65ncoded_proto_data\x18\x01 \x01(\x0c\x12\x0f\n\x07version\x18\x02 \x01(\x04\x12\x32\n\ttimestamp\x18\x03 \x01(\x0b\x32\x1f.aptos.util.timestamp.Timestamp\"\xe7\x01\n\x0cStreamStatus\x12:\n\x04type\x18\x01 \x01(\x0e\x32,.aptos.datastream.v1.StreamStatus.StatusType\x12\x15\n\rstart_version\x18\x02 \x01(\x04\x12\x18\n\x0b\x65nd_version\x18\x03 \x01(\x04H\x00\x88\x01\x01\"Z\n\nStatusType\x12\x1b\n\x17STATUS_TYPE_UNSPECIFIED\x10\x00\x12\x14\n\x10STATUS_TYPE_INIT\x10\x01\x12\x19\n\x15STATUS_TYPE_BATCH_END\x10\x02\x42\x0e\n\x0c_end_version\"\x82\x01\n\x14RawDatastreamRequest\x12\x1d\n\x10starting_version\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1f\n\x12transactions_count\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x13\n\x11_starting_versionB\x15\n\x13_transactions_count\"\xa3\x01\n\x15RawDatastreamResponse\x12\x33\n\x06status\x18\x01 \x01(\x0b\x32!.aptos.datastream.v1.StreamStatusH\x00\x12\x37\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\'.aptos.datastream.v1.TransactionsOutputH\x00\x12\x10\n\x08\x63hain_id\x18\x03 \x01(\rB\n\n\x08response2y\n\rIndexerStream\x12h\n\rRawDatastream\x12).aptos.datastream.v1.RawDatastreamRequest\x1a*.aptos.datastream.v1.RawDatastreamResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aptos.datastream.v1.datastream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSACTIONSOUTPUT._serialized_start=99
  _TRANSACTIONSOUTPUT._serialized_end=181
  _TRANSACTIONOUTPUT._serialized_start=183
  _TRANSACTIONOUTPUT._serialized_end=299
  _STREAMSTATUS._serialized_start=302
  _STREAMSTATUS._serialized_end=533
  _STREAMSTATUS_STATUSTYPE._serialized_start=427
  _STREAMSTATUS_STATUSTYPE._serialized_end=517
  _RAWDATASTREAMREQUEST._serialized_start=536
  _RAWDATASTREAMREQUEST._serialized_end=666
  _RAWDATASTREAMRESPONSE._serialized_start=669
  _RAWDATASTREAMRESPONSE._serialized_end=832
  _INDEXERSTREAM._serialized_start=834
  _INDEXERSTREAM._serialized_end=955
# @@protoc_insertion_point(module_scope)
