# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aptos/indexer/v1/raw_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from aptos.transaction.testing1.v1 import transaction_pb2 as aptos_dot_transaction_dot_testing1_dot_v1_dot_transaction__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61ptos/indexer/v1/raw_data.proto\x12\x10\x61ptos.indexer.v1\x1a/aptos/transaction/testing1/v1/transaction.proto\"\x84\x01\n\x16GetTransactionsRequest\x12\x1d\n\x10starting_version\x18\x01 \x01(\x04H\x00\x88\x01\x01\x12\x1f\n\x12transactions_count\x18\x02 \x01(\x04H\x01\x88\x01\x01\x42\x13\n\x11_starting_versionB\x15\n\x13_transactions_count\"|\n\x14TransactionsResponse\x12@\n\x0ctransactions\x18\x01 \x03(\x0b\x32*.aptos.transaction.testing1.v1.Transaction\x12\x15\n\x08\x63hain_id\x18\x02 \x01(\x04H\x00\x88\x01\x01\x42\x0b\n\t_chain_id2p\n\x07RawData\x12\x65\n\x0fGetTransactions\x12(.aptos.indexer.v1.GetTransactionsRequest\x1a&.aptos.indexer.v1.TransactionsResponse0\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aptos.indexer.v1.raw_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GETTRANSACTIONSREQUEST._serialized_start=103
  _GETTRANSACTIONSREQUEST._serialized_end=235
  _TRANSACTIONSRESPONSE._serialized_start=237
  _TRANSACTIONSRESPONSE._serialized_end=361
  _RAWDATA._serialized_start=363
  _RAWDATA._serialized_end=475
# @@protoc_insertion_point(module_scope)
