-- Your SQL goes here
ALTER TABLE objects ADD COLUMN IF NOT EXISTS is_token BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE objects ADD COLUMN IF NOT EXISTS is_fungible_asset BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE current_objects ADD COLUMN IF NOT EXISTS is_token BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE current_objects ADD COLUMN IF NOT EXISTS is_fungible_asset BOOLEAN NOT NULL DEFAULT FALSE;