name: Update SDK Dependency

on:
  repository_dispatch:
    types: [sdk-dependency-update]
  workflow_dispatch:
    inputs:
      branch_name:
        type: string
        default: "main"
      commit_hash:
        type: string
        default: "main"
      aptos_protos_commit_hash:
        type: string
        default: "main"

permissions:
  contents: write
  pull-requests: write
  id-token: write
jobs:
  update-the-dependency:
    runs-on: ubuntu-latest
    steps:
      - id: auth
        uses: "google-github-actions/auth@c200f3691d83b41bf9bbd8638997a462592937ed" # v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      - name: Get Secret Manager Secrets
        id: secrets
        uses: 'google-github-actions/get-secretmanager-secrets@2b5f97c5a4b9c105e64646762ad4fc3f5128e6f5' # v2
        with:
          secrets: |-
            token:aptos-ci/github-actions-repository-dispatch
      - run: sudo apt-get update && sudo apt-get install build-essential ca-certificates clang curl git libpq-dev libssl-dev pkg-config lsof lld libdw-dev --no-install-recommends --assume-yes
        shell: bash
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          token: ${{ steps.secrets.outputs.token }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1
        with:
          rustflags: --cfg tokio_unstable
          components: cargo clippy rustc rust-docs rust-std
      - name: Install toml
        run: cargo install toml-cli
      - name: Update the dependency
        env:
          COMMIT_HASH: ${{ github.event.inputs.commit_hash || github.event.client_payload.commit_hash }}
          APTOS_PROTOS_COMMIT_HASH: ${{ github.event.inputs.aptos_protos_commit_hash || github.event.client_payload.aptos_protos_commit_hash }}
          BRANCH_NAME: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
        run: |
          set -e
          # SDK commit hash SDK + framework + testing.
          toml set Cargo.toml workspace.dependencies.aptos-indexer-processor-sdk.rev "$COMMIT_HASH" > Cargo.tmp && mv Cargo.tmp Cargo.toml
          toml set Cargo.toml workspace.dependencies.aptos-indexer-processor-sdk-server-framework.rev "$COMMIT_HASH" > Cargo.tmp && mv Cargo.tmp Cargo.toml
          toml set Cargo.toml workspace.dependencies.aptos-indexer-testing-framework.rev "$COMMIT_HASH" > Cargo.tmp && mv Cargo.tmp Cargo.toml
          # Protos commit hash
          toml set Cargo.toml workspace.dependencies.aptos-protos.rev "$APTOS_PROTOS_COMMIT_HASH" > Cargo.tmp && mv Cargo.tmp Cargo.toml
          toml set Cargo.toml workspace.dependencies.aptos-indexer-test-transactions.rev "$APTOS_PROTOS_COMMIT_HASH" > Cargo.tmp && mv Cargo.tmp Cargo.toml
          cargo build || true
        working-directory: rust/
      - name: Configure Git user
        run: |
          git config --global user.name "Aptos Bot"
          git config --global user.email "aptos-bot@aptoslabs.com"
      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.token }}
          BRANCH_NAME: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
          COMMIT_HASH: ${{ github.event.inputs.commit_hash || github.event.client_payload.commit_hash }}
        run: |
           set -e
           branch_name="${BRANCH_NAME}-update-sdk"
           git checkout -b "$branch_name"
           git add Cargo.toml
           git add Cargo.lock
           git commit -m "Update sdk to $COMMIT_HASH"
           git push origin "$branch_name" --force
        working-directory: rust/
      - name: Create Pull Request
        env:
          GITHUB_TOKEN: ${{ steps.secrets.outputs.token }}
          BRANCH_NAME: ${{ github.event.inputs.branch_name || github.event.client_payload.branch_name }}
        run: |
          branch_name="${BRANCH_NAME}-update-sdk"
          gh pr create --title "Update sdk to upstream branch $BRANCH_NAME" \
                       --body "This PR updates sdk to new version." \
                       --base main \
                       --head "$branch_name" \
                       --label "indexer-sdk-update"
      - name: Run Integration Tests
        run: cargo test --manifest-path integration-tests/Cargo.toml
        working-directory: rust
